SELECT * FROM EMP;

DROP TABLE X,S,M;
CREATE TABLE M
(M1 CHAR(6), M2 VARCHAR(10));
CREATE TABLE S
(S1 CHAR(6), S2 VARCHAR(10));
CREATE TABLE X
(X1 CHAR(6), X2 VARCHAR(10));

INSERT INTO M VALUES('A','1');
INSERT INTO M VALUES('B','1');
INSERT INTO M VALUES('C','3');
INSERT INTO M VALUES(NULL, '3');

INSERT INTO S VALUES('A','X');
INSERT INTO S VALUES('B','Y');
INSERT INTO S VALUES(NULL, 'Z');

INSERT INTO X VALUES('A','DATA');
COMMIT;


SELECT * FROM X;
SELECT * FROM S;
SELECT * FROM M;

SELECT * FROM M INNER JOIN S ON M1 = S1;

SELECT * FROM M CROSS JOIN S;

SELECT * FROM M, S WHERE M1 = S1;

SELECT * FROM M LEFT OUTER JOIN S ON M1 = S1;
-- 없는건 NULL값으로 채워짐

SELECT * FROM M,S WHERE M1 = S1(+);
-- LEFT OUTER JOIN인 경우 오른쪽 컬럼에 +

SELECT * FROM M RIGHT OUTER JOIN S ON M1 = S1;

SELECT * FROM SALGRADE;


-- 사원의 월급이 몇등급인지 출력 : 사원 이름, 월급, 등급
SELECT ENAME, SAL, GRADE
FROM EMP JOIN SALGRADE ON (SAL BETWEEN LOSAL AND HISAL);


SELECT 사원.EMPNO, 사원.ENAME, 관리자.EMPNO, 관리자.ENAME
FROM EMP 사원, EMP 관리자
WHERE 사원.MGR = 관리자.EMPNO(+);
-- LEFT OUTER JOIN 하면 전부 값이나온데 KING은 왼쪽값만있고 오른쪽은 값이없어서 안나왔어

